source "http://rubygems.org"

gemspec

gem 'rake'
#gem 'websocket-eventmachine-server'
gem 'mysql2', '~> 0.3.20'
gem 'json'
gem 'redis'
gem 'redis-objects'
# Use Capistrano for deployment
group :development do
  gem 'capistrano', '~> 3.4.1'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'capistrano3-puma', '~> 1.0.0'
end
gem 'rbtrace'
